/**
 * FLUXENTA REDESIGN: MASTER CONSTANTS
 * All strings, colors, and configuration values are centralized here.
 */

export const COLORS = {
  CYAN_CUSTOM: "rgba(102, 252, 243, 1)",
  CYAN_GLOW: "rgba(102, 252, 243, 0.15)",
  CYAN_TINT: "rgba(102, 252, 241, 0.02)",
  WHITE_02: "rgba(255, 255, 255, 0.02)",
  WHITE_03: "rgba(255, 255, 255, 0.03)",
  WHITE_05: "rgba(255, 255, 255, 0.05)",
  WHITE_08: "rgba(255, 255, 255, 0.08)",
  WHITE_10: "rgba(255, 255, 255, 0.1)",
  TRANSPARENT: "rgba(255, 255, 255, 0)",
} as const;

export const SITE_STRINGS = {
  // 0. Navigation
  NAV: {
    LOGO: "fluxenta",
    MOBILE_MENU: "Menu",
    CLOSE: "Close",
    BOOK_CALL: "Book a Call",
    LINKS: [
      { name: "Squad", href: "#squad" },
      { name: "Growth", href: "#growth" },
      { name: "Tech", href: "#tech" },
      { name: "Contact", href: "#contact" },
    ],
  },

  // 1. Hero Section
  HERO: {
    HEADLINE: "Beyond Code. We Engineer Growth.",
    SUBTEXT: "We provide a dedicated team of experts to handle every part of your digital journey. From a Lead Strategist who oversees your project to our creative designers, expert developers, and marketing specialists, we work as one unit to turn your ideas into a successful business.",
    CTA: "Start Your Transformation",
  },

  // 2. Flux Core (Sticky Stacking)
  FLUX_CORE: {
    TITLE: "Your All-In-One Growth Team",
    SERVICES: [
      {
        id: "01",
        title: "Collaborative Product Architecture",
        description: "We don't just design, we co-author your vision. Our elite designers work alongside you to distill your most precise ideas into high-fidelity products, ensuring every pixel aligns with your strategic intent.",
        tag: "UI/UX • BRANDING",
      },
      {
        id: "02",
        title: "Scalable Systems Engineering",
        description: "We build for the next million users, not just the first. By utilizing a high-performance stack of Next.js, TypeScript, and edge-ready cloud architectures, we engineer resilient infrastructure that scales seamlessly alongside your business ambitions.",
        tag: "NEXT.JS • TYPESCRIPT • AWS",
      },
      {
        id: "03",
        title: "Growth Marketing",
        description: "Growth is a science, not a gamble. We deploy high-performance marketing stacks and precision content strategies designed to amplify your reach and maximize conversion, transforming your startup's core idea into a mass-market success story.",
        tag: "ADS • SEO • CONTENT",
      },
    ],
  },
} as const;

// 3. Growth Engine (Interactive Dashboard)
export const GROWTH_ENGINE = {
  TITLE: "Engineered for Impact",
  SUBTITLE: "High-precision data visualization of the ROI generated by our Media Marketing protocols. We turn complex performance metrics into clear, actionable growth narratives.",
  LABEL: "System_Status",
  STATUS_ACTIVE: "ROI_ENGINE_ACTIVE",
  TELEMETRY: "Telemetry",
  // SVG Paths for the growth curve
  GRAPH: {
    PATH: "M0,280 C50,270 100,280 150,240 S250,250 300,180 S400,190 500,120 S650,130 800,40",
    FILL: "M0,280 C50,270 100,280 150,240 S250,250 300,180 S400,190 500,120 S650,130 800,40 V300 H0 Z"
  },
  METRICS: [
    { label: "AVG. ROAS", value: "4.8x", trend: "+12%" },
    { label: "CONVERSION", value: "18.5%", trend: "+5.2%" },
    { label: "USER SCALE", value: "1.2M", trend: "Exponential" }
  ]
} as const;

export const ANIMATION_VARIANTS = {
  TYPEWRITER_SPEED: 0.05,
  SUBTEXT_FADE_DELAY: 1.2, 
  SPRING_TYPE: "spring",
  SPRING_DAMPING: 25,
  SPRING_STIFFNESS: 70,
  // Standard animation blocks for easy spreading
  FADE_IN: {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] }
  }
} as const;

export const SQUAD_SERVICES = [
  {
    id: '01',
    title: 'Collaborative Product Architecture',
    label: 'design',
    team: '1 Designers',
    description: "We don't just design, we co-author your vision. Our elite designers work alongside you to distill your most precise ideas into high-fidelity products, ensuring every pixel aligns with your strategic intent.",
    features: ['UI/UX Audit', 'Design Systems', 'Prototyping'],
    color: '#66FCF1',
  },
  {
    id: '02',
    title: 'Scalable Systems Engineering',
    label: 'engineer',
    team: '2 Developers',
    description: "We build for the next million users, not just the first. By utilizing a high-performance stack of Next.js, TypeScript, and edge-ready cloud architectures, we engineer resilient infrastructure that scales seamlessly alongside your business ambitions.",
    features: ['Custom SaaS', 'API Integration', 'Cloud Scaling'],
    color: '#A855F7',
  },
  {
    id: '03',
    title: 'Growth Marketing',
    label: 'scale',
    team: '3 Media Expert',
    description: "Growth is a science, not a gamble. We deploy high-performance marketing stacks and precision content strategies designed to amplify your reach and maximize conversion, transforming your startup's core idea into a mass-market success story.",
    features: ['Ad Strategy', 'Conversion Optimization', 'SEO'],
    color: '#FFFFFF',
  }
] as const;

export const ENGINE_METRICS = [
  { label: 'Avg. CAC Reduction', value: '-42%', status: 'optimized' },
  { label: 'ROAS Scalability', value: '5.8x', status: 'active' },
  { label: 'Pipeline Velocity', value: '+112%', status: 'accelerated' },
  { label: 'LTV/CAC Ratio', value: '4.2', status: 'stable' },
] as const;

export const TECH_STACK = {
  LABEL: "// 04 Technical Backbone",
  TITLE: "The Stack Behind the Scale.",
  SUBTITLE: "We build on a high-performance substrate engineered for rapid growth. By unifying Next.js edge-compute, Drizzle’s lightweight database logic, and AWS’s global delivery network, we ensure your product remains fast and reliable at any volume.",
  TECH_DESCRIPTION: "In short: your platform stays lightning-fast and unbreakable, no matter how many customers you reach.",
  
  ORBIT_ITEMS: [
    { id: 1, name: 'Next.js', src: 'https://cdn.worldvectorlogo.com/logos/next-js.svg' },
    { id: 2, name: 'TypeScript', src: 'https://cdn.worldvectorlogo.com/logos/typescript.svg' },
    { id: 3, name: 'Tailwind', src: 'https://cdn.worldvectorlogo.com/logos/tailwind-css-2.svg' },
    { id: 4, name: 'Framer', src: 'https://cdn.worldvectorlogo.com/logos/framer-motion.svg' },
    { id: 5, name: 'PostgreSQL', src: 'https://cdn.worldvectorlogo.com/logos/postgresql.svg' },
    { id: 6, name: 'Vercel', src: 'https://cdn.simpleicons.org/vercel/white' },
    { id: 7, name: 'Figma', src: 'https://cdn.simpleicons.org/figma/white' },
    { id: 8, name: 'Linear', src: 'https://cdn.worldvectorlogo.com/logos/linear-1.svg' },
  ],

  MARQUEE_LOGOS: [
    "Next.js", "TypeScript", "Tailwind", "Drizzle", "AWS", "PostgreSQL", 
    "Vercel", "Framer", "Stripe", "Redis", "Docker", "Sentry"
  ]
} as const;

export const ACTIVATION_GATE = {
  LABEL: "// 06 Activation Gate",
  TITLE: "Stop Hiring Vendors. Start Building with a Partner.",
  SUBTITLE: "Ready to scale your business?",
  BUTTON_TEXT: "Build With Us",
} as const;

export const FOOTER_STRINGS = {
  BRAND: "fluxenta.",
  COPYRIGHT: `© 2026 FLUXENTA INC`,
  LEGAL: [
    { name: "TERMS OF USE", href: "#" },
    { name: "PRIVACY POLICY", href: "#" },
    { name: "SUPPORT", href: "#" },
    { name: "TRUST CENTER", href: "#" },
  ],
} as const;

export const NAV_LINKS = [
  { name: "Squad", href: "#squad" },
  { name: "Growth", href: "#growth" },
  { name: "Tech", href: "#tech" },
  { name: "Contact", href: "#contact" },
] as const;

export const CONTACT_CONFIG = {
  CALENDLY_URL: "https://calendly.com/fluxenta-dev/new-meeting", // Replace with your link
  EMAIL: "hello@fluxenta.dev",
  OFFICE: "Remote",
  SOCIALS: [
    { name: "LinkedIn", href: "#" },
    { name: "Twitter", href: "#" }
  ]
} as const;